# Generated by Django 5.0.1 on 2024-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hw2', '0002_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
